add some metrics and set up otlp exporting
bluesky-social/indigo pull request #81
Opened 2023-03-21 17:39 UTC by whyrusleeping

2023-03-21 17:58 UTC, Jacob2161 requested changes
I've already added the receiver part for datadog-agent.

With this change (I added one env var)  we should be able to deploy with this for e.g. production:

```bash
BGS_ENVIRONMENT=production
OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4318
OTLP_EXPORT=true
```

2023-03-21 17:58 UTC, Jacob2161 commented on cmd/bigsky/main.go
> +			Name: "otlp-export",
```suggestion
			Name: "otlp-export",
			EnvVars: []string{"OTLP_EXPORT"},
```

2023-03-21 17:58 UTC, Jacob2161 commented on cmd/bigsky/main.go
> +			Name:    "env-type",
```suggestion
			Name:    "env-type",
			Usage: "environment type (test, staging, production)",
```

2023-04-12 19:12 UTC, whyrusleeping commented
this needs to be rebased and updated to use the latest opentrace metrics package

2023-07-21 22:18 UTC, whyrusleeping commented
this was merged in a different PR

2023-07-21 22:18 UTC, closed without merging